version: '3.8'

services:
  avogadro:
    image: avogadro-docker
    container_name: avogadro-docker
    environment:
      - DISPLAY=$DISPLAY
      - XAUTHORITY=/tmp/.XAuthority
      - QT_X11_NO_MITSHM=1
    volumes:
      - $XAUTHORITY:/tmp/.XAuthority
      - ./shared:/home/shared
    network_mode: host
    ipc: host
    tty: true
